# Makefile for libexcel.

.PHONY: all clean

SRCS = biffwriter.c worksheet.c format.c olewriter.c \
			 stream.c workbook.c

OBJS = $(SRCS:.c=.o)

CC = c:\lcc\bin\lcc
AR = c:\lcc\bin\lcclib

INTERNAL_CFLAGS = -A -I../include
CFLAGS= -O

LIB = libexcel
STATIC_LIB = libexcel.lib

all: $(LIB)

$(LIB): $(STATIC_LIB)

$(STATIC_LIB): $(OBJS)
	$(AR) /out:$(STATIC_LIB) $(OBJS)

clean:
	del $(OBJS) $(STATIC_LIB)

.c.o:
	$(CC) $(INTERNAL_CFLAGS) $(CFLAGS) -o $@ -c $<

